export const PROFICIENCY_LEVELS = [
  {
    id: 1,
    name: "Beginner",
    description:
      "Bạn có khả năng hiểu và sử dụng các từ vựng, cụm từ rất cơ bản, quen thuộc trong đời sống hàng ngày. Bạn có thể giới thiệu bản thân và những người khác, đặt và trả lời các câu hỏi về thông tin cá nhân như tên, tuổi, quốc tịch, nghề nghiệp, sở thích, gia đình, nơi ở, v.v. Bạn có thể giao tiếp ở mức độ tối thiểu nếu đối phương nói chậm rãi, rõ ràng và sẵn sàng giúp đỡ. Bạn có thể đọc và hiểu những câu đơn giản, như chỉ dẫn cơ bản, thông báo ngắn hoặc menu nhà hàng. Khả năng viết của bạn giới hạn trong việc điền vào biểu mẫu, viết thiệp chúc mừng hoặc ghi chú ngắn gọn.",
  },
  {
    id: 2,
    name: "Elementary",
    description:
      "Bạn có thể hiểu các câu và cụm từ phổ biến liên quan đến các chủ đề quen thuộc như gia đình, mua sắm, công việc, môi trường xung quanh. Bạn có thể tham gia vào các cuộc hội thoại đơn giản về các vấn đề thường ngày, miễn là đối phương nói chậm và rõ ràng. Bạn có thể mô tả về cuộc sống cá nhân, các hoạt động hàng ngày và nhu cầu thiết yếu của mình. Bạn có thể đọc và hiểu các văn bản ngắn như biển báo, hướng dẫn đơn giản hoặc email cá nhân. Khi viết, bạn có thể tạo ra các đoạn văn ngắn để mô tả sự kiện, nơi chốn hoặc kế hoạch của bản thân một cách cơ bản.",
  },
  {
    id: 3,
    name: "Intermediate",
    description:
      "Bạn có thể hiểu các ý chính của một bài phát biểu hoặc cuộc hội thoại về các chủ đề quen thuộc trong công việc, học tập hoặc giải trí. Bạn có thể xử lý hầu hết các tình huống khi đi du lịch đến một quốc gia sử dụng ngôn ngữ này. Bạn có thể viết những đoạn văn ngắn và rõ ràng về các chủ đề quan tâm hoặc trải nghiệm cá nhân. Khi giao tiếp, bạn có thể diễn đạt suy nghĩ của mình về sở thích, mục tiêu cá nhân, kinh nghiệm làm việc và đưa ra những lời khuyên đơn giản. Bạn có thể đọc và hiểu các bài báo ngắn, thư tín hoặc hướng dẫn có nội dung không quá chuyên sâu. Bạn có thể nêu quan điểm và giải thích một cách đơn giản về các sự kiện hoặc vấn đề hàng ngày.",
  },
  {
    id: 4,
    name: "Upper Intermediate",
    description:
      "Bạn có thể hiểu các bài phát biểu dài hơn và theo dõi các cuộc trò chuyện về các chủ đề trừu tượng hoặc chuyên môn. Bạn có thể giao tiếp trôi chảy và tự nhiên với người bản ngữ mà không gặp khó khăn đáng kể. Bạn có thể tham gia vào các cuộc tranh luận, trình bày quan điểm và bảo vệ ý kiến của mình bằng lập luận rõ ràng. Khi viết, bạn có thể soạn thảo các văn bản chi tiết về nhiều chủ đề khác nhau, sử dụng cấu trúc ngữ pháp phức tạp hơn. Bạn có thể đọc hiểu các bài báo, bài luận và tài liệu kỹ thuật có độ phức tạp vừa phải. Bạn có thể xử lý tốt các tình huống trong công việc hoặc học thuật, bao gồm cả việc thuyết trình, viết báo cáo hoặc email chuyên nghiệp.",
  },
  {
    id: 5,
    name: "Advanced",
    description:
      "Bạn có thể hiểu những văn bản dài và phức tạp, bao gồm các nội dung chuyên ngành hoặc học thuật. Bạn có thể diễn đạt ý tưởng một cách trôi chảy, chính xác và linh hoạt, ít mắc lỗi ngữ pháp. Bạn có thể giao tiếp hiệu quả trong môi trường chuyên nghiệp, tham gia các cuộc thảo luận chuyên sâu và đưa ra lập luận sắc bén. Bạn có thể đọc hiểu và phân tích các văn bản mang tính học thuật, văn chương hoặc kỹ thuật cao. Khi viết, bạn có thể tạo ra các bài luận, báo cáo hoặc tài liệu chuyên môn với cấu trúc logic, rõ ràng và mạch lạc. Bạn có thể thích nghi với nhiều ngữ cảnh giao tiếp khác nhau, bao gồm hội họp, phỏng vấn, đàm phán hoặc thảo luận nhóm một cách tự nhiên.",
  },
  {
    id: 6,
    name: "Proficient",
    description:
      "Bạn có thể hiểu và phân tích gần như bất kỳ loại văn bản hoặc cuộc hội thoại nào, kể cả các tài liệu chuyên môn, bài báo học thuật, tác phẩm văn học hoặc diễn thuyết chính trị. Bạn có thể giao tiếp với độ chính xác cao, diễn đạt tư duy phức tạp mà không gặp bất kỳ trở ngại nào. Bạn có thể điều chỉnh phong cách ngôn ngữ của mình phù hợp với từng ngữ cảnh, từ giao tiếp hàng ngày đến các bài phát biểu chính thức. Khi viết, bạn có thể soạn thảo văn bản với độ tinh tế cao, sử dụng cấu trúc câu đa dạng, ngôn ngữ giàu hình ảnh và thể hiện được sắc thái ý nghĩa tinh tế. Bạn có thể xử lý những tình huống giao tiếp phức tạp nhất, bao gồm tranh luận chuyên sâu, thuyết trình cấp cao hoặc sáng tác văn bản nghệ thuật với chất lượng cao.",
  },
] as const;

export const VISITED_KEYS = {
  chat: "has-visited-chat",
  dictionary: "has-visited-dictionary",
};

export const CHAT_HISTORY_KEY = "chat-history";
export const RECENT_DICTIONARY_SEARCHES_KEY = "recent-dictionary-searches";

export const SAMPLE_DICTIONARY_KEYWORDS = [
  "accomplish",
  "resilient",
  "endeavor",
  "persistent",
  "innovative",
  "efficient",
  "versatile",
  "meticulous",
  "profound",
  "ambiguous",
  "diligent",
  "authentic",
  "genuine",
  "spontaneous",
  "tremendous",
  "significant",
  "inevitable",
  "dynamic",
  "crucial",
  "essential",
  "break down",
  "carry out",
  "look up to",
  "give up",
  "put off",
  "figure out",
  "get along",
  "bring up",
  "hold on",
  "come across",
  "take off",
  "look forward to",
  "run into",
  "catch up",
  "stand out",
  "turn down",
  "work out",
  "put up with",
  "set up",
  "hang out",
  "methodology",
  "hypothesis",
  "empirical",
  "paradigm",
  "synthesis",
  "preliminary",
  "subsequent",
  "comprehensive",
  "fundamental",
  "perspective",
  "theoretical",
  "analytical",
  "coherent",
  "correlate",
  "derivative",
  "qualitative",
  "quantitative",
  "abstract",
  "conceptual",
  "implicit",
  "piece of cake",
  "break the ice",
  "hit the nail on the head",
  "under the weather",
  "bite the bullet",
  "blessing in disguise",
  "cost an arm and a leg",
  "pull yourself together",
  "beat around the bush",
  "once in a blue moon",
  "get cold feet",
  "let the cat out of the bag",
  "kill two birds with one stone",
  "barking up the wrong tree",
  "cut corners",
  "spill the beans",
  "tie the knot",
  "paint the town red",
  "call it a day",
  "face the music",
  "outsource",
  "stakeholder",
  "leverage",
  "implementation",
  "initiative",
  "benchmark",
  "sustainable",
  "optimize",
  "facilitate",
  "strategize",
  "incentivize",
  "monetize",
  "scalable",
  "synergy",
  "metrics",
  "portfolio",
  "acquisition",
  "revenue",
  "diversify",
  "innovative",
];

export const FEATURES = [
  {
    title: "TỪ ĐIỂN",
    englishTitle: "Tra cứu thông minh",
    description:
      "Truy cập định nghĩa từ, thành ngữ và cụm động từ với ngữ cảnh của từ.",
    href: "/dictionary",
    gradient: "linear-gradient(135deg, #3b82f6, #22d3ee)",
  },
  {
    title: "TƯ VẤN",
    englishTitle: "Trò chuyện với gia sư ảo",
    description:
      "Tương tác với gia sư AI để được hướng dẫn và hỗ trợ tự học tiếng Anh.",
    href: "/chat",
    gradient: "linear-gradient(135deg, #f97316, #facc15)",
  },
];
